### PR TITLE
Fix incorrect environment entity in climate regulators.

### PR DESCRIPTION
**Pull request by bloxgate**
Was still using the old self.environment instead of self.sbenvironment

### CODE REVIEW

**Comment by bloxgate** [comment]
Was just informed they're still broken. Will try adding default values later tonight.

**Comment by N3X15** [comment]
Lemme know when it's ready.

**Comment by bloxgate** [comment]
Will do, I've applied the latest commits to my server. I should be able to figure out if its a problem with the code getting the values within a day.

**Comment by bloxgate** [comment]
Looks like that debug information actually fixed the problem on my server at least. Closes #14

**Pull request merged**
